# make load_data become a packet to resolve import issue

# PLEASE DO NOT DELETE THIS!!!!!
# PLEASE DO NOT DELETE THIS!!!!!
# PLEASE DO NOT DELETE THIS!!!!!
# PLEASE DO NOT DELETE THIS!!!!!
# PLEASE DO NOT DELETE THIS!!!!!
# PLEASE DO NOT DELETE THIS!!!!!
# PLEASE DO NOT DELETE THIS!!!!!